remote-controller:
  hosts:
    ansible:
      ansible_host: 127.0.0.1
      ansible_connection: local

web:
  hosts:
    web-ddriham-1:
      ansible_host: 10.0.47.209
    web-ddriham-2:
      ansible_host: 10.0.33.46

db:
  hosts:
    db-ddriham:
      ansible_host: 10.0.40.200

vars:
  web:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true

vars:
  db:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true


