---
  - name: IIS playbook
    hosts: windows
    tasks:
      - name: Install WEB Server IIS
        ansible.windows.win_feature:
          name: Web-Server
          state: present
          include_sub_features: true
          include_management_tools: true
        register: win_feature
